# Generated by Django 5.1.1 on 2024-10-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('zipcode', models.CharField(max_length=30)),
                ('role', models.IntegerField()),
                ('type', models.IntegerField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
