# Generated by Django 5.1.1 on 2024-10-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_remove_user_date_joined'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
