# Generated by Django 5.1.1 on 2024-12-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_user_availability_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
