# Generated by Django 5.1.1 on 2024-12-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
    ]
