# Generated by Django 5.1.1 on 2024-12-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_rename_post_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
