# Generated by Django 5.1.4 on 2024-12-07 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_rename_posts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timeline', models.CharField(max_length=100)),
                ('approach', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Application.post')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.user')),
            ],
        ),
    ]
